name: Deploy Spring Boot to Backend EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      # Step 1: Upload JAR file to Bastion Host
      - name: Upload JAR to Bastion
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/"

      # Step 2: SSH into Bastion and Copy JAR to Backend EC2, then Restart App
      - name: SSH into Bastion & Deploy to Backend EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Verifying JAR file exists on Bastion..."
            ls -lah /home/ec2-user/target/
            echo "Copying JAR to Backend EC2..."
            scp -o StrictHostKeyChecking=no -i ~/traderdeck-key.pem /home/ec2-user/target/backend-0.0.1-SNAPSHOT.jar ec2-user@10.16.78.89:/home/ec2-user/

            echo "Appending env variables on Backend EC2..."
            ssh -o StrictHostKeyChecking=no -i ~/traderdeck-key.pem ec2-user@10.16.78.89 "cat >> /home/ec2-user/.env <<EOF
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            BEDROCK_FLOW_ID=${{ secrets.BEDROCK_FLOW_ID }}
            BEDROCK_FLOW_ALIAS_ID=${{ secrets.BEDROCK_FLOW_ALIAS_ID }}
            BEDROCK_MOCK_ENABLED=${{ secrets.BEDROCK_MOCK_ENABLED }}
            EOF"

            echo "Deploying to Backend EC2..."
            ssh -o StrictHostKeyChecking=no -i ~/traderdeck-key.pem ec2-user@10.16.78.89 '
              echo "Stopping existing Spring Boot application..."
              pkill -f "java .* -jar .*backend-0.0.1-SNAPSHOT.jar" || echo "No existing application to stop"
              sleep 2

              echo "Sourcing env..."
              set -a
              . /home/ec2-user/.env
              set +a
              env | egrep "^(DB_|AWS_|BEDROCK_)" || true

              echo "Starting new deployment..."
              nohup java -jar /home/ec2-user/backend-0.0.1-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 &
              NEW_PID=$!
              sleep 10

              echo "Checking if application is running..."
              if ps -p $NEW_PID > /dev/null; then
                echo "Application is running"
                tail -n 50 /home/ec2-user/app.log || true
              else
                echo "Application failed to start"
                cat /home/ec2-user/app.log || true
                exit 1
              fi
            '
